# Generated by Django 6.0.6 on 2026-06-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
