# Generated by Django 6.0.6 on 2026-06-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='saved_table_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='saved_item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
